### ISSUE TITLE
What is up with FA2?

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/michelson-semantics#194]
The type difference in `update_token_pool_interal` between FA1.2 and FA2: https://gitlab.com/dexter2tz/dexter2tz/-/blob/8a5792a56e0143042926c3ca8bff7d7068a541c3/dexter.mligo#L52

Here we see that `update_token_pool_internal` is the biggest "major" change between FA1.2 and FA2. Why does this have so much larger of a type in FA2 than FA1.2?

Where the type difference is used in the codebase: https://gitlab.com/dexter2tz/dexter2tz/-/blob/8a5792a56e0143042926c3ca8bff7d7068a541c3/dexter.mligo#L425

**Comment by hjorthjort** [comment]
Here are links describing what FA2 and FA1.2 are:
FA2: https://gitlab.com/tzip/tzip/-/blob/master/proposals/tzip-12/tzip-12.md#balance_of , https://gitlab.com/tzip/tzip/-/tree/master/#current-tzips
FA1 https://gitlab.com/tzip/tzip/-/blob/master/proposals/tzip-5/tzip-5.md#getbalance
FA1.2 https://gitlab.com/tzip/tzip/-/blob/master/proposals/tzip-7/tzip-7.md

**Comment by hjorthjort** [comment]
The token is compiled with version FA1.2, i.e. the the `FA2` compile variable is false, and the `#ifdef FA2...` statements are treated accordingly.
