### ISSUE TITLE
Add real entrypoint semantics for `CONTRACT` and `TRANSFER_TOKENS`

### ISSUE THREAD

**Issue by hjorthjort** [runtimeverification/michelson-semantics#236]
Attempted in #229, but it contains other things as well. Make a new PR with just the necessary changes for the external contract interactions instruction to work properly.

The `knownaddrs` cell:
Change the paramtype cell to contain a map from address plus field annotations, e.g. `tzXXXX . %getBalance` to type, e.g. `pair nat nat`.

**Comment by sskeirik** [comment]
This was recently merged in the entrypoints PR.
