### ISSUE TITLE
Simplify comparison reasoning for the prover

### ISSUE THREAD

**Issue by hjorthjort** [runtimeverification/michelson-semantics#237]
Change the implementation of `#DoCompare`: most kinds of well-typed comparisons can be reduced into total comparison functions (without the need for #if) which seems to work better with K's Haskell backend.

It's currently incorporated in #229, but should be separated into its own PR.

**Comment by sskeirik** [comment]
This was address by adding `#Ceil` rules to the `#DoCompare` function.
