### ISSUE TITLE
Proof by induction of safety properties (storage invariants) in the presence of reentrancy

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/michelson-semantics#265]
Starting point: https://github.com/runtimeverification/michelson-semantics/blob/master/tests/proofs/dexter/dexter-properties.md#storage-invariant

The proofs will be in the context that (i) arbitrary reentrancy is possible following each function call, (ii) arbitrary order for function calls.

Assumptions are also present for this, which we will document.

**Comment by daejunpark** [comment]
Done by https://github.com/runtimeverification/michelson-semantics/pull/276
