### ISSUE TITLE
Use recent `--mode mockup` flag to simplify the cross-validation test harness

### ISSUE THREAD

**Issue by sskeirik** [runtimeverification/michelson-semantics#50]
Currently, the cross-validation test harness relies on starting a Tezos sandbox to run our tests. A recent update to the client added a mockup mode (http://tezos.gitlab.io/user/mockup.html) that allows many functions to be run without starting a Tezos sandbox, including:

- type checking
- running scripts

This means we should be entirely eliminate our dependency on starting a sandbox in our test suite which:
- _should_ improve performance by increasing available parallelism, i.e. many interpreters will service our requests instead of a single node process
- _will_ simplify our test harness because it will no longer have any non-input file state that needs to be considered --- and there is no potential for resource leaks from failing to shut down our sandbox

EDIT: When running `tezos-client`, one can use `tezos-client --mode mockup man` gives a CLI reference --- though I'm not sure if this reference is for just mockup mode supported commands or for all commands.

**Comment by rafoo** [comment]
> When running tezos-client, one can use tezos-client --mode mockup man gives a CLI reference --- though I'm not sure if this reference is for just mockup mode supported commands or for all commands.

It is for all client commands. `--mode` is a global flag so you can use it with all client commands but some (such as `bake`) will fail.
